### ISSUE TITLE
有什么开发计划吗

### ISSUE THREAD

**Issue by maicss** [dearjoey/scripts#1]
现在有什么开发计划吗，我觉得我可以帮点忙。

**Comment by 120318** [comment]
目前没有明确的站点支持计划。
脚本比较简单，想要支持哪些站点，或者觉得哪里需要改进，直接提交PR？

**Comment by maicss** [comment]
我是刚玩PT不到一个月，现在手里有的站还很少。先确定一些咱们俩都有的，方便测试验证还是我随便来？

**Comment by 120318** [comment]
随便来就行☺️> 我是刚玩PT不到一个月，现在手里有的站还很少。先确定一些咱们俩都有的，方便测试验证还是我随便来？

**Comment by maicss** [comment]
你怎么开发的啊，能设置成自动reload吗？

**Comment by 120318** [comment]
> 你怎么开发的啊，能设置成自动reload吗？

TG细聊吧。

**Comment by maicss** [comment]
所以怎么加TG 😂
